[package]
name = "async_programming"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
futures = "0.3"
reqwest = "0.11.16"

[lib]
name = "timer_future"
path = "src/lib.rs"
